-- Placeholder: canonical M2M body is ReportDashboardPostgresRosterSql.VisaAppProgressViewSql.
-- ReportDashboardSqlViewResource.Load redirects this leaf, so ModuleUpdater and the
-- host-start heal share one definition. Editing this file has no effect.
