-- Invitation Completed (V) — PostgreSQL.
DROP VIEW IF EXISTS vw_rd_application_via_ministry_invitation_completed_by_period_category_type;
CREATE VIEW vw_rd_application_via_ministry_invitation_completed_by_period_category_type AS
SELECT * FROM vw_rd_application_via_ministry_invitation_completed_base;
