// <auto-generated by scripts/local/Generate-ApplicationTypeConfigurationSeed.ps1 Ã¢â‚¬â€ do not edit manually>
using Visa2026.Module.BusinessObjects;

namespace Visa2026.Module.DatabaseUpdate;

internal static partial class ApplicationTypeConfigurationSeed
{
    private static ApplicationTypeConfigurationRow[] CreateRows() => new ApplicationTypeConfigurationRow[]
    {
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Border_Zone_Permission",
            NameTm = "Serhet Ãaka ÃœÃ§in Rugsatnama Almak",
            Code = "get_border_zone",
            PdfForm_Code = 25,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 30,
            ShowProjectContract = true, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = false, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = true, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Cancel_BZ",
            NameTm = "Serhet Ãaka ÃœÃ§in Rugsatnamany Ãatyrmak",
            Code = "cancel_borderzone",
            PdfForm_Code = 25,
            LifecycleStage = ApplicationLifecycleStage.Exit,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 10,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Cancel_App",
            NameTm = "ÃÃ¼ztutmany Ãatyrmak",
            Code = "cancel_application",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Exit,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Cancel_Visa_and_WP_Ext",
            NameTm = "Wiza we IÅŸ Rugsatnamany Uzaltmak Barada ÃÃ¼ztutmany Ãatyrmak",
            Code = "cancel_visa_wp_ext",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Exit,
            Category = ApplicationTypeCategory.Employee,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = true, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Cancel_Visa_Ext",
            NameTm = "Wizany Uzaltmak Barada ÃÃ¼ztutmany Ãatyrmak",
            Code = "cancel_visa_ext",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Exit,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Inv",
            NameTm = "Ã‡akylyk Almak",
            Code = "get_invitation",
            PdfForm_Code = 2,
            LifecycleStage = ApplicationLifecycleStage.Entry,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 30,
            ShowProjectContract = true, ShowVisaPeriod = true, ShowVisaCategory = true, ShowUrgency = true, ShowInvitations = true, ShowRejections = true, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = false, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = true, ShowCurrentEducation = true, ShowInvitationItemIsIssued = true, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = true, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = false, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = true
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Inv_FM",
            NameTm = "Ã‡akylyk Almak FM",
            Code = "get_invitation",
            PdfForm_Code = 2,
            LifecycleStage = ApplicationLifecycleStage.Entry,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 30,
            ShowProjectContract = true, ShowVisaPeriod = true, ShowVisaCategory = true, ShowUrgency = true, ShowInvitations = true, ShowRejections = true, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = false, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = true, ShowCurrentEducation = true, ShowInvitationItemIsIssued = true, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = true, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = false, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = true
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Sevice_Passport",
            NameTm = "Gulluk Pasporty ÃœÃ§in Ã‡akylyk Almak",
            Code = "get_invitation",
            PdfForm_Code = 2,
            LifecycleStage = ApplicationLifecycleStage.Entry,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 10,
            ShowProjectContract = true, ShowVisaPeriod = true, ShowVisaCategory = true, ShowUrgency = true, ShowInvitations = false, ShowRejections = true, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = false, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = true, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = true, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = true, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = true
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Inv_According_to_WP",
            NameTm = "Ä°ÅŸ Rugsatnama gÃ¶rÃ¤ Ã‡akylyk Almak",
            Code = "get_invitation",
            PdfForm_Code = 2,
            LifecycleStage = ApplicationLifecycleStage.Entry,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 30,
            ShowProjectContract = true, ShowVisaPeriod = true, ShowVisaCategory = true, ShowUrgency = true, ShowInvitations = true, ShowRejections = true, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = false, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = true, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = true, ShowCurrentMedicalRecord = true, ShowCurrentEducation = true, ShowInvitationItemIsIssued = true, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = true, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = true, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = true
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Change_Inv",
            NameTm = "Ã‡akylygy Ã¼Ã½tgetmek",
            Code = "change_invitation",
            PdfForm_Code = 2,
            LifecycleStage = ApplicationLifecycleStage.Entry,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 5,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = true, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = true, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = true, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Cancel_Inv",
            NameTm = "Ã‡akylygy Ãatyrmak",
            Code = "cancel_invitation",
            PdfForm_Code = 2,
            LifecycleStage = ApplicationLifecycleStage.Exit,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 5,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = true, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = true, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = true, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Inv_And_WP",
            NameTm = "Ã‡akylyk we IÅŸ Rugsatnamasyny Almak",
            Code = "get_invitation_wp",
            PdfForm_Code = 2,
            LifecycleStage = ApplicationLifecycleStage.Entry,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 45,
            ShowProjectContract = true, ShowVisaPeriod = true, ShowVisaCategory = true, ShowUrgency = true, ShowInvitations = true, ShowRejections = true, ShowWorkPermits = true, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = false, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = true, ShowCurrentMedicalRecord = true, ShowCurrentEducation = true, ShowInvitationItemIsIssued = true, ShowWorkPermitItemIsIssued = true, ShowRejectionIssued = true, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = false, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Cancel_Inv_WP",
            NameTm = "Ã‡akylyk we IÅŸ Rugsatnamasyny Ãatyrmak",
            Code = "cancel_invitation_wp",
            PdfForm_Code = 2,
            LifecycleStage = ApplicationLifecycleStage.Entry,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 5,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = true, ShowCurrentInvitationItem = true, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = true, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = false, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = true, ShowInvitationItemIsChanged = true, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = true, ShowPreviousWorkPermitItem = true, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Reg_Check_In",
            NameTm = "Hasaba Almak (DaÅŸary Ã½urtdan gelmegi sebÃ¤pli)",
            Code = "check_in",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = true, ShowVisas = false, ShowApplicationItems = false, ShowApplicationReason = false, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Reg_Check_In_Internal",
            NameTm = "Hasaba Almak (WelaÃ½atdan gelmegi sebÃ¤pli)",
            Code = "check_in",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = true, ShowVisas = false, ShowApplicationItems = false, ShowApplicationReason = false, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = true, ShowToCity = true, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Reg_Info_Change_Passport",
            NameTm = "Hasaba alyÅŸ maglumatyÅˆ Ã¼Ã½tgemegi (Pasport Ã‡alÄ±ÅŸmagy)",
            Code = "check_in_info_change",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = true, ShowVisas = false, ShowApplicationItems = false, ShowApplicationReason = false, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Reg_Info_Change_Visa",
            NameTm = "Hasaba alyÅŸ maglumatyÅˆ Ã¼Ã½tgemegi (Visa Ã‡alyÅŸmagy)",
            Code = "check_in_info_change",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = true, ShowVisas = false, ShowApplicationItems = false, ShowApplicationReason = false, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Reg_Info_Change_Address",
            NameTm = "Hasaba alyÅŸ maglumatyÅˆ Ã¼Ã½tgemegi (Salgy Ã‡alyÅŸmagy)",
            Code = "check_in_info_change",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = true, ShowVisas = false, ShowApplicationItems = false, ShowApplicationReason = false, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Reg_ext",
            NameTm = "Hasaba alyÅŸy uzaltmak",
            Code = "check_in_extention",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = true, ShowVisas = false, ShowApplicationItems = false, ShowApplicationReason = false, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Reg_Check_Out",
            NameTm = "Hasapdan Ã‡ykarmak (DaÅŸary Ã½urda gitmegi)",
            Code = "check_out",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Exit,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = true, ShowVisas = false, ShowApplicationItems = false, ShowApplicationReason = false, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Reg_Check_Out_Internal",
            NameTm = "Hasapdan Ã‡ykarmak (BaÅŸga welaÃ½ata gitmegi)",
            Code = "check_out",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Exit,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = true, ShowVisas = false, ShowApplicationItems = false, ShowApplicationReason = false, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = true, ShowToCity = true, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Business_Trip_Departure",
            NameTm = "IÅŸ Saparyna Gitmek",
            Code = "business_trip",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Entry,
            Category = ApplicationTypeCategory.Employee,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = false, ShowApplicationReason = false, ShowMigrationService = true, ShowBusinessTrips = true, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = false, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = false, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = true, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Business_Trip_Arrival",
            NameTm = "IÅŸ Saparyna Gelmek",
            Code = "business_trip",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Entry,
            Category = ApplicationTypeCategory.Employee,
            DurationInDays = 2,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = false, ShowApplicationReason = false, ShowMigrationService = true, ShowBusinessTrips = true, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = false, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = false, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = true, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Cancel_Visa",
            NameTm = "Wizany Ãatyrmak",
            Code = "cancel_visa",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Exit,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 10,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = true, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Visa_Ext_According_to_WP",
            NameTm = "IÅŸ Rugsatnamasyna GÃ¶rÃ¤ Wizany Uzaltmak",
            Code = "visa_extension",
            PdfForm_Code = 3,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 45,
            ShowProjectContract = true, ShowVisaPeriod = true, ShowVisaCategory = true, ShowUrgency = true, ShowInvitations = false, ShowRejections = true, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = true, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = true, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = true, ShowCurrentMedicalRecord = true, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = true, ShowVisaIssued = true, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = true
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Visa_Ext",
            NameTm = "Wiza MÃ¶hletini Uzaltmak",
            Code = "visa_extension",
            PdfForm_Code = 3,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 45,
            ShowProjectContract = true, ShowVisaPeriod = true, ShowVisaCategory = true, ShowUrgency = true, ShowInvitations = false, ShowRejections = true, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = true, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = false, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = true, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = true, ShowVisaIssued = true, ShowVisaIsCancelled = false, ShowVisaIsChanged = false, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = true
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Exit_Visa",
            NameTm = "Ã‡ykyÅŸ  Wiza ResmileÅŸdirmek",
            Code = "visa_exit",
            PdfForm_Code = 3,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 45,
            ShowProjectContract = true, ShowVisaPeriod = true, ShowVisaCategory = true, ShowUrgency = true, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = true, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = false, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = true, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = true, ShowVisaIssued = true, ShowVisaIsCancelled = false, ShowVisaIsChanged = false, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Change_Visa_Category",
            NameTm = "Wiza KategoriÃ½asyny Ã¼Ã½tgetmek",
            Code = "visa_category_change",
            PdfForm_Code = 8,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 10,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = true, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = true, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = true, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Change_Passport",
            NameTm = "Wizany KP>TÃ¤ze Pasporta GeÃ§irmek",
            Code = "pasport_change",
            PdfForm_Code = 6,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 10,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = true, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = true, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = true, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = true, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Visa_Ext_FM",
            NameTm = "Wiza MÃ¶hletini Uzaltmak FM",
            Code = "visa_extension",
            PdfForm_Code = 6,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 10,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = true, ShowInvitations = false, ShowRejections = true, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = true, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = true, ShowVisaIssued = true, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = true
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Visa_For_New_Born_FM",
            NameTm = "TÃ¤ze dogulan Ã§aga wiza resmileÅŸdirmek FM",
            Code = "visa_extension",
            PdfForm_Code = 6,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.Both,
            DurationInDays = 10,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = true, ShowInvitations = false, ShowRejections = true, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = true, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = false, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = true, ShowVisaIssued = true, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Cancel_Visa_and_WP",
            NameTm = "Wiza we IÅŸ Rugsatnamany Ãatyrmak",
            Code = "cancel_visa_wp",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Exit,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 10,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = true, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = true, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = true, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = true, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Visa_and_WP_Ext",
            NameTm = "Wiza we IÅŸ Rugsatnamasyny Uzaltmak",
            Code = "extend_visa_wp",
            PdfForm_Code = 3,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 45,
            ShowProjectContract = true, ShowVisaPeriod = true, ShowVisaCategory = true, ShowUrgency = true, ShowInvitations = false, ShowRejections = true, ShowWorkPermits = true, ShowRegistrations = false, ShowVisas = true, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = false, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = true, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = true, ShowCurrentMedicalRecord = true, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = true, ShowRejectionIssued = true, ShowVisaIssued = true, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = true
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_WP_Ext",
            NameTm = "IÅŸ Rugsatnamasyny Uzaltmak",
            Code = "workpermit_extension",
            PdfForm_Code = 3,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 45,
            ShowProjectContract = true, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = true, ShowWorkPermits = true, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = false, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = true, ShowCurrentWorkPermitItem = true, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = true, ShowCurrentEmployeeContract = true, ShowCurrentMedicalRecord = true, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = true, ShowRejectionIssued = true, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Cancell_WP",
            NameTm = "IÅŸ Rugsatnamany Ãatyrmak",
            Code = "cancel_workpermit",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Exit,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 30,
            ShowProjectContract = false, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = false, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = true, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = true, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = true, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = false, ShowBorderZoneLocation = false, ShowMovementPermitLocation = false, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = true, ShowVisaType = false
        },
        new ApplicationTypeConfigurationRow
        {
            Name = "App_Additional_WP_location",
            NameTm = "IÅŸ Rugsatnama goÅŸmaÃ§a  barjak Ã½eri",
            Code = "change_workpermit",
            PdfForm_Code = 0,
            LifecycleStage = ApplicationLifecycleStage.Stay,
            Category = ApplicationTypeCategory.FamilyMember,
            DurationInDays = 30,
            ShowProjectContract = true, ShowVisaPeriod = false, ShowVisaCategory = false, ShowUrgency = false, ShowInvitations = false, ShowRejections = false, ShowWorkPermits = true, ShowRegistrations = false, ShowVisas = false, ShowApplicationItems = true, ShowApplicationReason = true, ShowMigrationService = false, ShowBusinessTrips = false, ShowPreviousPassport = false, ShowPreviousVisa = false, ShowCurrentVisa = false, ShowCurrentWorkPermitItem = true, ShowCurrentInvitationItem = false, ShowCurrentAddressOfResidence = false, ShowCurrentEmployeeContract = false, ShowCurrentMedicalRecord = false, ShowCurrentEducation = true, ShowInvitationItemIsIssued = false, ShowWorkPermitItemIsIssued = false, ShowRejectionIssued = false, ShowVisaIssued = false, ShowVisaIsCancelled = false, ShowVisaIsChanged = true, ShowInvitationItemIsCancelled = false, ShowWorkPermitItemIsCancelled = false, ShowInvitationItemIsChanged = false, ShowWorkPermitItemIsChanged = true, ShowBorderZoneLocation = false, ShowMovementPermitLocation = true, ShowFromCity = false, ShowToCity = false, ShowPreviousInvitationItem = false, ShowPreviousWorkPermitItem = false, ShowVisaType = false
        },
    };
}
