-- Local disposable PostgreSQL: wipe imported transactional BOs.
-- Keeps: lookup catalogs, ProjectContracts, ApprovalLegProfiles, PermissionPolicy*, ApplicationProfiles, etc.
-- Table names follow the ApplicationProfileInstance cutover; ApplicationProfileInstancePeople is a
-- skip-navigation join (ApplicationProfileInstanceId + PersonId only, no roster-line ID). Truncate
-- it together with ResolvedLinks, otherwise Wave 2b reimport sees stale membership.
-- IMPORTANT: Do NOT truncate FileData (CASCADE would wipe UserReportTemplates / ProjectContractDocuments).
-- After truncate, optionally: DELETE FROM "FileData" WHERE "ID" NOT IN (SELECT "TemplateFileID" FROM "UserReportTemplates" WHERE "TemplateFileID" IS NOT NULL);
BEGIN;
TRUNCATE TABLE
  "ApplicationProfileInstanceProgresses",
  "ApplicationProfileInstancePersonResolvedLinks",
  "ApplicationProfileInstancePeople",
  "ApplicationProfileInstanceApprovalLegSnapshots",
  "ApplicationProfileInstances",
  "WorkPermitItems",
  "WorkPermitLocations",
  "WorkPermitDocuments",
  "WorkPermitImages",
  "WorkPermits",
  "InvitationItems",
  "InvitationDocuments",
  "InvitationImages",
  "Invitations",
  "BorderZoneItem",
  "BorderZoneDocuments",
  "BorderZones",
  "RejectionItems",
  "RejectionDocuments",
  "RejectionImages",
  "Rejections",
  "TravelHistories",
  "BusinessTripAddress",
  "VisaDocument",
  "VisaImages",
  "Visas",
  "PassportDocuments",
  "PassportImages",
  "Passports",
  "EducationDocument",
  "EducationImages",
  "Educations",
  "EmployeePositionHistories",
  "EmployeeSalaries",
  "WorkDuties",
  "AddressOfResidenceDocuments",
  "AddressOfResidenceImages",
  "AddressesOfResidence",
  "MedicalRecordDocuments",
  "MedicalRecordImage",
  "MedicalRecords",
  "PersonDocuments",
  "PersonFamilyRelationDocuments",
  "FamilyMemberImages",
  "LodgingDocuments",
  "LodgingImages",
  "PdfGenerationBatches",
  "WordReportGenerationBatches",
  "BoStateSnapshots",
  "StateChangeLogs",
  "SyncRuleLogs",
  "AuditData",
  "AuditEFCoreWeakReferences",
  "ApplicationRuntimeLogs",
  "UserFeedbacks",
  "People"
RESTART IDENTITY CASCADE;
COMMIT;