# Parses LOOKUPS.md Application Type table → ApplicationTypeConfigurationSeed.Data.cs
param(
    [string]$LookupsPath = (Join-Path $PSScriptRoot '..\..\LOOKUPS.md'),
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\..\Visa2026.Module\DatabaseUpdate\ApplicationTypeConfigurationSeed.Data.cs')
)

$ErrorActionPreference = 'Stop'
$lines = Get-Content -LiteralPath $LookupsPath -Encoding UTF8
$startIdx = -1
for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -eq '## Application Type') { $startIdx = $i; break }
}
if ($startIdx -lt 0) { throw "Application Type section not found in $LookupsPath" }

# ## Application Type → blank → OData line → blank → header → separator → data
$headerLine = $lines[$startIdx + 4]
$headers = @($headerLine.Trim('|').Split('|') | ForEach-Object { $_.Trim() })
$rows = New-Object System.Collections.Generic.List[hashtable]
for ($i = $startIdx + 6; $i -lt $lines.Count; $i++) {
    $line = $lines[$i]
    if ($line -eq '## City') { break }
    if (-not $line.StartsWith('|')) { continue }
    $cells = @($line.Trim('|').Split('|') | ForEach-Object { $_.Trim() })
    if ($cells.Count -lt $headers.Count) { continue }
    $name = $cells[$headers.IndexOf('Name')]
    if ([string]::IsNullOrWhiteSpace($name)) { continue }
    $row = @{}
    for ($c = 0; $c -lt $headers.Count; $c++) { $row[$headers[$c]] = $cells[$c] }
    $rows.Add($row)
}

function To-BoolLiteral([string]$v) { if ($v -eq '1') { return 'true' } else { return 'false' } }
function To-Int([string]$v) { if ([string]::IsNullOrWhiteSpace($v)) { return 0 }; return [int]$v }
function Esc([string]$v) { return ($v -replace '\\', '\\\\' -replace '"', '\"') }

$lifecycle = @{ '0' = 'ApplicationLifecycleStage.Entry'; '1' = 'ApplicationLifecycleStage.Stay'; '2' = 'ApplicationLifecycleStage.Exit' }
$category = @{ '0' = 'ApplicationTypeCategory.Employee'; '1' = 'ApplicationTypeCategory.FamilyMember'; '2' = 'ApplicationTypeCategory.Both' }

$boolProps = @(
    'ShowProjectContract','ShowVisaPeriod','ShowVisaCategory','ShowUrgency','ShowInvitations','ShowRejections',
    'ShowWorkPermits','ShowRegistrations','ShowVisas','ShowApplicationItems','ShowApplicationReason','ShowMigrationService',
    'ShowBusinessTrips','ShowPreviousPassport','ShowPreviousVisa','ShowCurrentVisa','ShowCurrentWorkPermitItem','ShowCurrentInvitationItem',
    'ShowCurrentAddressOfResidence','ShowCurrentEmployeeContract','ShowCurrentMedicalRecord','ShowCurrentEducation',
    'ShowInvitationItemIsIssued','ShowWorkPermitItemIsIssued','ShowRejectionIssued','ShowVisaIssued','ShowVisaIsCancelled',
    'ShowVisaIsChanged','ShowInvitationItemIsCancelled','ShowWorkPermitItemIsCancelled','ShowInvitationItemIsChanged',
    'ShowWorkPermitItemIsChanged','ShowBorderZoneLocation','ShowMovementPermitLocation','ShowFromCity','ShowToCity',
    'ShowPreviousInvitationItem','ShowPreviousWorkPermitItem','ShowVisaType'
)
function Get-BoolColumn([string]$propName) {
    if ($propName -eq 'ShowPreviousVisa') { return 'PreviousVisa' }
    return $propName
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated by scripts/local/Generate-ApplicationTypeConfigurationSeed.ps1 - do not edit manually>')
[void]$sb.AppendLine('using Visa2026.Module.BusinessObjects;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace Visa2026.Module.DatabaseUpdate;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('internal static partial class ApplicationTypeConfigurationSeed')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    private static ApplicationTypeConfigurationRow[] CreateRows() => new ApplicationTypeConfigurationRow[]')
[void]$sb.AppendLine('    {')

foreach ($r in $rows) {
    $name = Esc $r['Name']
    $nameTm = Esc $r['NameTm']
    $code = Esc $r['Code']
    $lsKey = [string]$r['LifecycleStage']
    $catKey = [string]$r['Category']
    if (-not $lifecycle.ContainsKey($lsKey)) { throw "Unknown LifecycleStage '$lsKey' for $name" }
    if (-not $category.ContainsKey($catKey)) { throw "Unknown Category '$catKey' for $name" }
    $ls = $lifecycle[$lsKey]
    $cat = $category[$catKey]
    $pdf = To-Int $r['PdfForm_Code']
    $dur = To-Int $r['DurationInDays']
    $boolArgs = New-Object System.Collections.Generic.List[string]
    foreach ($prop in $boolProps) {
        $col = Get-BoolColumn $prop
        $val = To-BoolLiteral $r[$col]
        $boolArgs.Add("$prop = $val")
    }

    [void]$sb.AppendLine('        new ApplicationTypeConfigurationRow')
    [void]$sb.AppendLine('        {')
    [void]$sb.AppendLine("            Name = `"$name`",")
    [void]$sb.AppendLine("            NameTm = `"$nameTm`",")
    [void]$sb.AppendLine("            Code = `"$code`",")
    [void]$sb.AppendLine("            PdfForm_Code = $pdf,")
    [void]$sb.AppendLine("            LifecycleStage = $ls,")
    [void]$sb.AppendLine("            Category = $cat,")
    [void]$sb.AppendLine("            DurationInDays = $dur,")
    [void]$sb.AppendLine("            $($boolArgs -join ', ')")
    [void]$sb.AppendLine('        },')
}

[void]$sb.AppendLine('    };')
[void]$sb.AppendLine('}')

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutputPath, $sb.ToString(), $utf8NoBom)
Write-Host "Wrote $($rows.Count) rows to $OutputPath"
