# Generates (legacy) ApplicationTypeConfigurationSeed.Data.cs from a single JSON catalog:
#   Visa2026.Module/DatabaseUpdate/LookupCatalogs/ApplicationTypeConfigurationCatalog.json
param(
    [string]$CatalogPath = (Join-Path $PSScriptRoot '..\..\Visa2026.Module\DatabaseUpdate\LookupCatalogs\ApplicationTypeConfigurationCatalog.json'),
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\..\Visa2026.Module\DatabaseUpdate\ApplicationTypeConfigurationSeed.Data.cs')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $CatalogPath)) {
    throw "ApplicationType configuration catalog not found: $CatalogPath"
}

$catalog = Get-Content -LiteralPath $CatalogPath -Raw -Encoding UTF8 | ConvertFrom-Json
if ($null -eq $catalog.rows -or $catalog.rows.Count -lt 1) {
    throw "No rows found in $CatalogPath"
}

function Esc([string]$v) { return ($v -replace '\\', '\\\\' -replace '"', '\"') }

$boolProps = @(
    'ShowProjectContract','ShowVisaPeriod','ShowVisaCategory','ShowUrgency','ShowInvitations','ShowRejections',
    'ShowWorkPermits','ShowRegistrations','ShowVisas','ShowApplicationItems','ShowApplicationReason','ShowMigrationService',
    'ShowBusinessTrips','ShowPreviousPassport','ShowCurrentVisa','ShowCurrentWorkPermitItem','ShowCurrentInvitationItem',
    'ShowCurrentAddressOfResidence','ShowCurrentEmployeeContract','ShowCurrentMedicalRecord','ShowCurrentEducation',
    'ShowInvitationItemIsIssued','ShowWorkPermitItemIsIssued','ShowRejectionIssued','ShowVisaIssued','ShowVisaIsCancelled',
    'ShowVisaIsChanged','ShowInvitationItemIsCancelled','ShowWorkPermitItemIsCancelled','ShowInvitationItemIsChanged',
    'ShowWorkPermitItemIsChanged','ShowBorderZoneLocation','ShowMovementPermitLocation','ShowFromCity','ShowToCity',
    'ShowPreviousInvitationItem','ShowPreviousWorkPermitItem','ShowVisaType','ShowNextVisa'
)

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated by scripts/local/Generate-ApplicationTypeConfigurationSeed.ps1 - do not edit manually>')
[void]$sb.AppendLine('using Visa2026.Module.BusinessObjects;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace Visa2026.Module.DatabaseUpdate;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('internal static partial class ApplicationTypeConfigurationSeed')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    private static ApplicationTypeConfigurationRow[] CreateRows() => new ApplicationTypeConfigurationRow[]')
[void]$sb.AppendLine('    {')

foreach ($r in $catalog.rows) {
    $name = Esc ([string]$r.Name)
    $nameTm = Esc ([string]$r.NameTm)
    $code = Esc ([string]$r.Code)
    $ls = "ApplicationLifecycleStage.$([string]$r.LifecycleStage)"
    $cat = "ApplicationTypeCategory.$([string]$r.Category)"
    $pdf = [int]$r.PdfForm_Code
    $dur = [int]$r.DurationInDays

    $flags = @{}
    if ($null -ne $r.Flags) {
        foreach ($p in $r.Flags.PSObject.Properties) { $flags[$p.Name] = [bool]$p.Value }
    }

    $boolArgs = New-Object System.Collections.Generic.List[string]
    foreach ($prop in $boolProps) {
        $val = $false
        if ($flags.ContainsKey($prop)) { $val = [bool]$flags[$prop] }
        $boolArgs.Add("$prop = $($val.ToString().ToLowerInvariant())")
    }

    [void]$sb.AppendLine('        new ApplicationTypeConfigurationRow')
    [void]$sb.AppendLine('        {')
    [void]$sb.AppendLine("            Name = `"$name`",")
    [void]$sb.AppendLine("            NameTm = `"$nameTm`",")
    [void]$sb.AppendLine("            Code = `"$code`",")
    [void]$sb.AppendLine("            PdfForm_Code = $pdf,")
    [void]$sb.AppendLine("            LifecycleStage = $ls,")
    [void]$sb.AppendLine("            Category = $cat,")
    [void]$sb.AppendLine("            DurationInDays = $dur,")
    [void]$sb.AppendLine("            $($boolArgs -join ', ')")
    [void]$sb.AppendLine('        },')
}

[void]$sb.AppendLine('    };')
[void]$sb.AppendLine('}')

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutputPath, $sb.ToString(), $utf8NoBom)
Write-Host "Wrote $($catalog.rows.Count) rows to $OutputPath"
